import google.generativeai as genai
from PIL import Image
import os

def get_image_ad_feedback(uploaded_image_file):
    """
    Analyzes an uploaded image using the Gemini Vision model.
    
    Returns two things:
    1. The path to a pre-made "improved" image (to keep the demo visual).
    2. The LIVE text feedback generated by the Gemini API based on the image.
    """
    try:
        model = genai.GenerativeModel('gemini-2.5-flash-preview-05-20')
        
        # Open the image file uploaded by the user
        image = Image.open(uploaded_image_file)
        
        prompt = """
            You are an expert marketing designer named 'AdAstra'.
            Analyze the attached ad image, which performed poorly. Provide feedback to improve its click-through rate.
            Structure your response using Markdown with two sections:

            ### 1. Visual Analysis & Feedback
            (Provide 3 specific, actionable bullet points focusing on visual elements like color contrast, call-to-action (CTA) button visibility, font choice, and overall composition.)

            ### 2. Prompt for an Improved Version
            (Write a short, descriptive text prompt that could be given to an image generation AI like Midjourney to create a better version of this ad.)
        """
        
        # This is the key for multimodal input: send both the text prompt and the image
        response = model.generate_content([prompt, image])
        
        # For the demo, we still return the path to our pre-made "improved" image
        improved_image_path = os.path.join("images", "ad_improved.png")
        
        return improved_image_path, response.text

    except Exception as e:
        # Return an error message and the path to the placeholder image
        improved_image_path = os.path.join("images", "ad_improved.png")
        return improved_image_path, f"An error occurred with the Gemini API: {e}"